sudo: required
language: android
android:
 components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
before_script:
 - chmod +x generate-apk.sh
 - cd PowerUp
 - chmod +x gradlew
script:
 - ./gradlew assembleDebug
after_success:
  - cd ..
  - ./generate-apk.sh
